FROM eclipse-temurin:21-jre
WORKDIR /app
COPY build/libs/ ./
RUN find . -maxdepth 1 -type f -name "*.jar" ! -name "*-plain.jar" | head -n 1 | xargs -r -I{} mv "{}" app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]