name: Bug
description: 버그 제보
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 문제 상황
      placeholder: 어떤 문제가 발생했는지 작성
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 재현 방법
      placeholder: |
        1. 무엇을 했는지
        2. 어떤 문제가 났는지