name: Feature
description: 기능 추가
title: "[FEAT] "
labels: ["feature"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 설명
      placeholder: 어떤 기능인지 작성
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: 작업 내용
      placeholder: |
        - [ ] 엔티티
        - [ ] 서비스
        - [ ] 컨트롤러
        - [ ] 테스트